name: Alpine 3 amd64

on:
  push:
    branches: [ main, linux, alpine, alpine3 ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  alpine-3-amd64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        file: alpine-3-amd64.Dockerfile
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tankard:alpine-3-amd64
