name: Windows 2019 amd64

on:
  push:
    branches: [ windows, windows2019 ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  windows-2019-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      run: |
        net stop docker
        dockerd --unregister-service
        dockerd --register-service --storage-opt "size=40G"
        net start docker
        docker build . -f windows-2019-amd64.Dockerfile -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tankard:windows-2019-amd64

    - name: Push
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        docker image push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tankard:windows-2019-amd64
